# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'win1803'

steps:
- powershell: |
    iwr -outf generator.zip https://www.aka.ms/azurestackmarketplaceitem
    Expand-Archive generator.zip -DestinationPath generator
    ".\generator\Azure Stack Marketplace Item Generator and Sample\AzureGalleryPackageGenerato\AzureGalleryPackager.exe" -m .\kubernetes\template\manifest.json -o .
  displayName: 'Do stuff'
